version: "3"
services:
  client:
    image: client
    build: ./frontend/
    stdin_open: true
    ports :
      - "3000:3000"
    networks:
      - knowledgeManagementApp
    depends_on:
      - server  
  server:
    image: server
    build: ./backend/
    ports:
       - "4000:4000"
    networks:
      - knowledgeManagementApp

networks:
  knowledgeManagementApp:
    driver: bridge

